#!/bin/bash
set -e

source colors_zenburn

ICON_100="\uf240"
ICON_75="\uf241"
ICON_50="\uf242"
ICON_25="\uf243"
ICON_0="\uef244"
ICON_BOLT="\uf0e7"

while true; do
    bat_state=`acpi -b`
    bat_perc=`echo $bat_state | cut -d, -f2 | sed 's/[^0-9]//g'`
    if [ "$bat_perc" -ge "75" ]; then
        icon=$ICON_100
        col=$COL_GREEN
    elif [ "$bat_perc" -ge "50" ]; then
        icon=$ICON_75
        col=$COL_GREEN
    elif [ "$bat_perc" -ge "25" ]; then
        icon=$ICON_50
        col=$COL_YELLOW
    else
        icon=$ICON_25
        col=$COL_RED
    fi

    if echo $bat_state | grep Charging > /dev/null; then
        icon="$ICON_BOLT"
    elif echo $bat_state | grep Discharging > /dev/null; then
        sym=""
    elif echo $bat_state | grep Full > /dev/null; then
        icon="$ICON_BOLT"
    else
        sym=""
    fi

    echo -e "BAT$icon $sym%{F$col}$bat_perc%{F-}"
    sleep 30
done
