#!/bin/bash
set -e

ICON_IM="\uf11c"

FCITX_PROFILE=~/.config/fcitx/profile

# Do a fake echo when the script starts to force an update
# alsactl monitor needs to be forced to write immediately rather than buffer,
# otherwise the output can't be redirected

while true; do
    im_name=`cat $FCITX_PROFILE | grep IMName | cut -d= -f2`
    state=`fcitx-remote`
    if [ "$state" == "2" ]; then
        case $im_name in
            sunpinyin)
                im="PY"
                ;;
            chewing)
                im="ZY"
                ;;
            *)
                im=$im_name
        esac
    else
        im="EN"
    fi
    echo -e "IME$ICON_IM $im"

    # Wait for fcitx profile to change
    inotifywait -e close_write $FCITX_PROFILE $FCITX_STATE > /dev/null 2>&1
done
