#!/bin/bash

source colors_zenburn

ICON_STOPPED="\uf001"
ICON_PLAYING="\uf04b"
ICON_PAUSED="\uf04c"

TITLE_LEN=28
ARTIST_LEN=13

# Do a fake echo when the script starts to force an update
(echo "player"; mpc idleloop player) | while read -r line; do
    title=`mpc current -f %title%`

    state=`test -n "$title" && echo $title|| echo "stopped"`
    if [ "${state}" == "stopped" ]; then
        echo -e "MPD${ICON_STOPPED} off"
    else
        if mpc status | grep playing > /dev/null; then
            icon=$ICON_PLAYING
        else
            icon=$ICON_PAUSED
        fi
        artist=`mpc current -f %artist%`

        title=`echo $title | truncate.sh $TITLE_LEN`
        artist=`echo $artist | truncate.sh $ARTIST_LEN`

        echo -e "MPD${icon}" \
                "%{F$COL_BLUE}${artist}%{F-}" \
                "%{F$COL_YELLOW}${title}%{F-}"
    fi
done
