#!/bin/bash
set -e

source colors_zenburn

INTERFACE="wlp3s0"
STRENGTH_CHECK_INTERVAL=30

PROCESSING_TEXT="\u00b7\u00b7\u00b7"
ICON_CONNECTED_NO_INTERNET="\uf110"
ICON_CONNECTED="\uf1eb"
ICON_NO_CONNECTION="\uf1eb"

colorize_strength() {
    if [ "$1" -ge "80" ]; then
        COL=$COL_GREEN
    elif [ "$1" -ge "60" ]; then
        COL=$COL_YELLOW
    #elif [ "$1" -ge "30" ]; then
        #COL=$COL_RED
    else
        COL=$COL_RED
    fi
    echo -e "%{F$COL}$1%{F-}"
}

# We need to the fake intial message when the script starts,
# since most likely the network is already up
if iwgetid -r > /dev/null; then
    first_message="$INTERFACE: connected"
else
    first_message="$INTERFACE: disconnected"
fi

(echo $first_message; \
nmcli m) | while read -r line;
do
    if echo $line | grep $INTERFACE > /dev/null; then
        msg=`echo $line | sed 's/.*: //g'`
        case "$msg" in
            "connecting (configuring)")
                echo -e "NET$ICON_CONNECTED_NO_INTERNET $PROCESSING_TEXT"
                ;;
            "connected")
                while true; do
                    STRENGTH=`nmcli --fields IN-USE,SIGNAL \
                        dev wifi list | sed '/*  [0-9]/!d;s/[* ]//g'`
                    echo -e "NET$ICON_CONNECTED" \
                       "`colorize_strength ${STRENGTH}`"
                    sleep $STRENGTH_CHECK_INTERVAL;
                done &
                MONITOR_PID=$!
                SSID=`iwgetid -r`
                ;;
            "deactivating")
                kill $MONITOR_PID
                wait $MONITOR_PID 2>/dev/null
                echo -e "NET$ICON_CONNECTED_NO_INTERNET ..."
                ;;
            "disconnected")
                echo -e "NET$ICON_NO_CONNECTION off"
                ;;
            *)
                ;;
        esac
    fi
done
