#! /bin/sh

cd $(dirname $0)
source $(dirname $0)/config
source $(dirname $0)/colors_zenburn

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

WIDGETS=(battery bspwm_state brightness clock fcitx focused_window_title mpd network pacman volume)
for widget in ${WIDGETS[@]}; do
    # Kill existing instances
    pkill -f widgets/$widget
    # Start new instance
    ./widgets/$widget > "$PANEL_FIFO" &
done

panel_bar < "$PANEL_FIFO" | \
    lemonbar -a 32 -n "$PANEL_WM_NAME" \ -g x$PANEL_HEIGHT \
    -f "$PANEL_FONT" -o "$PANEL_FONT_OFFSET" \
    -f "$ICON_FONT" -o "$ICON_FONT_OFFSET" \
    -f "$CJK_FONT" -o "$CJK_FONT_OFFSET" \
    -F "$PANEL_COLOR_FG" -B "$PANEL_COLOR_BG" -u 4 | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
    sleep 0.05
    wid=$(xdo id -a "$PANEL_WM_NAME")
    tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
