#! /bin/sh
#
# Example panel for lemonbar

ICON_DESKTOP_FREE="\uf1db"
ICON_DESKTOP_OCCUPIED="\uf111"

while read -r line ; do
    case $line in
        BAT*)
            # Battery
            bat="${line#???}"
            ;;
        BRI*)
            # Brightness
            bri="${line#???}"
            ;;
        CLK*)
            # Date and time
            clk="${line#???}"
            ;;
        IME*)
            # Input method
            ime="${line#???}"
            ;;
        MPD*)
            # mpd state
            mpd="${line#???}"
            ;;
        NET*)
            # Network
            net="${line#???}"
            ;;
        VOL*)
            # Volume
            vol="${line#???}"
            ;;
        FWT*)
            # Focused window title
            title="${line#???}"
            ;;
        WMS*)
            # bspwm's state
            wmstate="${line#???}"
            ;;
    esac
    printf "%s\n" "%{l} ${wmstate} ${title}%{c}%{r}${mpd} ${ime} ${bri} ${vol} ${net} ${bat} ${clk} "
done
