#! /bin/sh
#
# Example panel for lemonbar

ICON_DESKTOP_FREE="\uf1db"
ICON_DESKTOP_OCCUPIED="\uf111"

while read -r line ; do
    case $line in
        BAT*)
            # Battery
            bat="${line#???}"
            ;;
        BRI*)
            # Brightness
            bri="${line#???}"
            ;;
        CLK*)
            # Date and time
            clk="${line#???}"
            ;;
        FWT*)
            # Focused window title
            title="${line#???}"
            ;;
        IME*)
            # Input method
            ime="${line#???}"
            ;;
        MPD*)
            # mpd state
            mpd="${line#???}"
            ;;
        NET*)
            # Network
            net="${line#???}"
            ;;
        PAC*)
            # Pacman update count. The widget doesn't appear if there are no
            # Pacman updates, so we don't put a space after it in the panel
            # to avoid extra blank space in that case. If there are updates,
            # we add the space back.
            pac="${line#???}"
            if [ ! -z "$pac" ]; then
                pac="$pac "
            fi
            ;;
        VOL*)
            # Volume
            vol="${line#???}"
            ;;
        WMS*)
            # bspwm's state
            wmstate="${line#???}"
            ;;
    esac
    printf "%s\n" "%{l} ${wmstate} ${title}%{c}%{r}${mpd} ${pac}${ime} ${bri} ${vol} ${net} ${bat} ${clk} "
done
