#! /bin/sh

sxhkd &

#green: bspc config focused_border_color \#bfebbf
bspc config focused_border_color \#8cd0d3
bspc config border_width         4
bspc config window_gap          12
bspc config top_padding         36

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d 1 2 3 4 5

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Kill panel instances from previous sessions
pkill panel
pkill panel_bar
# Start new panel instance
PATH=$PATH:~/.config/bspwm/panel/:~/.scripts ~/.config/bspwm/panel/panel &
